# Generated by Django 3.1 on 2020-08-20 08:20

import Job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0007_auto_20200820_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=Job.models.upload_image),
        ),
    ]
