# Generated by Django 3.1 on 2020-08-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0009_job_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('link', models.URLField()),
                ('cv', models.FileField(upload_to='apply/')),
                ('coverletter', models.TextField()),
            ],
        ),
    ]
